---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    if: false
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
