---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    if: false
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
