---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - uses: actions/cache@387e18722e6ff315b24a3b8b071feddd27b7bf7e # v3.4.2
